"""gfx1100 Gemma 4 kernel wrappers."""

from hipengine.kernels.hip_gfx1100.gemma4.gemma4_norm import (
    build_gemma4_norm,
    gemma4_add_rmsnorm_scale_bf16,
    gemma4_branch_add_bf16,
    gemma4_dense_combine_rmsnorm_scale_bf16,
    gemma4_expert_weight_scale_f32,
    gemma4_head_rmsnorm_f32w_bf16,
    gemma4_multi_rmsnorm_bf16,
    gemma4_rmsnorm_f32w_bf16,
    gemma4_rmsnorm_f32w_f32,
    gemma4_rmsnorm_weightless_bf16,
    gemma4_router_prescale_bf16,
    plan_gemma4_norm_build,
    register_gemma4_norm_kernels,
)
from hipengine.kernels.hip_gfx1100.gemma4.gemma4_attention import (
    build_gemma4_attention,
    gemma4_attention_prefill_bf16,
    gemma4_attention_prefill_f32,
    plan_gemma4_attention_build,
    register_gemma4_attention_kernels,
)
from hipengine.kernels.hip_gfx1100.gemma4.gemma4_attention_int8 import (
    build_gemma4_attention_int8,
    gemma4_attention_decode_int8_per_token_head_spans,
    plan_gemma4_attention_int8_build,
    register_gemma4_int8_attention_kernels,
)
from hipengine.kernels.hip_gfx1100.gemma4.gemma4_moe import (
    build_gemma4_moe,
    gemma4_gelu_tanh_mul_bf16,
    gemma4_gelu_tanh_mul_split_bf16,
    gemma4_moe_lane_to_row_i32,
    gemma4_moe_weighted_accumulate_bf16,
    gemma4_moe_zero_bf16,
    plan_gemma4_moe_build,
    register_gemma4_moe_kernels,
)
from hipengine.kernels.hip_gfx1100.gemma4.gemma4_rope import (
    GEMMA4_ROPE_DEFAULT_TYPE,
    GEMMA4_ROPE_PROPORTIONAL_TYPE,
    gemma4_rope_angles,
    gemma4_rope_cos_sin_tables,
    gemma4_rope_inverse_frequencies,
    gemma4_rotate_split_half,
)
from hipengine.kernels.hip_gfx1100.gemma4.gemma4_rotary import (
    build_gemma4_rotary,
    gemma4_k_to_v_bf16,
    gemma4_partial_rotary_bf16,
    gemma4_partial_rotary_f32,
    plan_gemma4_rotary_build,
    register_gemma4_rotary_kernels,
)
from hipengine.kernels.hip_gfx1100.gemma4.gemma4_router import (
    gemma4_router_topk_bf16,
    gemma4_router_topk_fused_bf16,
    register_gemma4_router_kernels,
)

__all__ = [
    "GEMMA4_ROPE_DEFAULT_TYPE",
    "GEMMA4_ROPE_PROPORTIONAL_TYPE",
    "build_gemma4_attention",
    "build_gemma4_attention_int8",
    "build_gemma4_moe",
    "build_gemma4_norm",
    "build_gemma4_rotary",
    "gemma4_add_rmsnorm_scale_bf16",
    "gemma4_attention_decode_int8_per_token_head_spans",
    "gemma4_attention_prefill_bf16",
    "gemma4_attention_prefill_f32",
    "gemma4_branch_add_bf16",
    "gemma4_dense_combine_rmsnorm_scale_bf16",
    "gemma4_expert_weight_scale_f32",
    "gemma4_gelu_tanh_mul_bf16",
    "gemma4_gelu_tanh_mul_split_bf16",
    "gemma4_head_rmsnorm_f32w_bf16",
    "gemma4_k_to_v_bf16",
    "gemma4_moe_lane_to_row_i32",
    "gemma4_moe_weighted_accumulate_bf16",
    "gemma4_multi_rmsnorm_bf16",
    "gemma4_moe_zero_bf16",
    "gemma4_partial_rotary_bf16",
    "gemma4_partial_rotary_f32",
    "gemma4_rmsnorm_f32w_bf16",
    "gemma4_rmsnorm_f32w_f32",
    "gemma4_rmsnorm_weightless_bf16",
    "gemma4_rope_angles",
    "gemma4_rope_cos_sin_tables",
    "gemma4_rope_inverse_frequencies",
    "gemma4_rotate_split_half",
    "gemma4_router_prescale_bf16",
    "gemma4_router_topk_bf16",
    "gemma4_router_topk_fused_bf16",
    "plan_gemma4_attention_build",
    "plan_gemma4_attention_int8_build",
    "plan_gemma4_moe_build",
    "plan_gemma4_norm_build",
    "plan_gemma4_rotary_build",
    "register_gemma4_attention_kernels",
    "register_gemma4_int8_attention_kernels",
    "register_gemma4_moe_kernels",
    "register_gemma4_norm_kernels",
    "register_gemma4_rotary_kernels",
    "register_gemma4_router_kernels",
]
