"""Dispatch, batching, and fusion planning."""

from hipengine.dispatch.batch import (
    ActiveBatch,
    BatchShapeKey,
    BatchSlot,
    PhysicalBatchGroup,
    RequestState,
    SlotMove,
    WorkItem,
    WorkKind,
    plan_physical_batch_groups,
)
from hipengine.dispatch.batch_width import (
    BatchWidthGroup,
    BatchWidthPartitionPlan,
    NativeBatchWidthProfile,
    plan_batch_width_partition,
)
from hipengine.dispatch.fusion import BoundKernel, FusionPlanner, KernelPlanStep, resolve_plan
from hipengine.dispatch.kv import (
    KVKernelSelection,
    PagedAttnDecodeKind,
    PagedAttnPrefillKind,
    PagedKVWriteKind,
    bind_paged_attn_decode,
    bind_paged_attn_prefill,
    bind_paged_kv_write,
    plan_paged_attn_decode,
    plan_paged_attn_prefill,
    plan_paged_kv_write,
    resolve_paged_attn_decode,
    resolve_paged_attn_prefill,
    resolve_paged_kv_write,
)
from hipengine.dispatch.projection import (
    ProjectionDispatchCandidate,
    ProjectionDispatchDecision,
    ProjectionDispatchEvidence,
    ProjectionKernelSelection,
    plan_projection_dispatch,
    plan_projection_dispatch_from_artifact,
    projection_dispatch_candidates_from_artifact,
    projection_dispatch_evidence_payload_blockers,
    projection_dispatch_candidates_from_json,
)
from hipengine.dispatch.sampling import (
    BatchSamplerDispatchDecision,
    BatchSamplerMode,
    batch_sampler_equality_payload_blockers,
    plan_batch_sampler_dispatch,
)

__all__ = [
    "ActiveBatch",
    "BatchSamplerDispatchDecision",
    "BatchSamplerMode",
    "BatchShapeKey",
    "BatchSlot",
    "BatchWidthGroup",
    "BatchWidthPartitionPlan",
    "BoundKernel",
    "FusionPlanner",
    "KVKernelSelection",
    "KernelPlanStep",
    "PagedAttnDecodeKind",
    "PagedAttnPrefillKind",
    "PagedKVWriteKind",
    "PhysicalBatchGroup",
    "ProjectionDispatchCandidate",
    "ProjectionDispatchDecision",
    "ProjectionDispatchEvidence",
    "ProjectionKernelSelection",
    "NativeBatchWidthProfile",
    "RequestState",
    "SlotMove",
    "WorkItem",
    "WorkKind",
    "batch_sampler_equality_payload_blockers",
    "bind_paged_attn_decode",
    "bind_paged_attn_prefill",
    "bind_paged_kv_write",
    "plan_paged_attn_decode",
    "plan_paged_attn_prefill",
    "plan_paged_kv_write",
    "plan_projection_dispatch",
    "plan_projection_dispatch_from_artifact",
    "projection_dispatch_candidates_from_artifact",
    "projection_dispatch_candidates_from_json",
    "projection_dispatch_evidence_payload_blockers",
    "plan_batch_sampler_dispatch",
    "plan_batch_width_partition",
    "plan_physical_batch_groups",
    "resolve_paged_attn_decode",
    "resolve_paged_attn_prefill",
    "resolve_paged_kv_write",
    "resolve_plan",
]
