"""RED tests: DFlash2 CPU reference vs golden fixtures from the z-lab/dflash torch reference.

The golden fixtures were generated by ``scripts/gen_dflash2_cpu_fixtures.py``
running the verbatim reference math (GroupedDynamicCausalConv,
CandidateSelector) from ``~/dflash/dflash/model.py`` @ 07ebd93. These tests
pin the exact contract the native DFlash2 kernels must reproduce.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from hipengine.kernels.cpu_reference.dflash2 import candidate_selector_select
from hipengine.kernels.cpu_reference.fixtures import load_fixture, run_fixture
from hipengine.kernels.registry import resolve

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "cpu_reference"

CONV_FIXTURES = (
    "dflash2_conv_prepare.json",
    "dflash2_conv_finish.json",
)


@pytest.mark.parametrize("fixture_name", CONV_FIXTURES)
def test_dflash2_grouped_conv_matches_torch_reference(fixture_name: str) -> None:
    fixture = load_fixture(FIXTURES / fixture_name)
    result = run_fixture(fixture)

    assert result.passed, (
        f"{fixture.name}: max_abs={result.max_abs:.3e} max_rel={result.max_rel:.3e} "
        f"vs {fixture.tolerances}"
    )


def test_dflash2_selector_path_matches_torch_reference() -> None:
    fixture = load_fixture(FIXTURES / "dflash2_selector_path.json")
    result = run_fixture(fixture)

    assert result.passed, (
        f"{fixture.name}: max_abs={result.max_abs:.3e} max_rel={result.max_rel:.3e}"
    )


def test_dflash2_selector_full_result_matches_torch_reference() -> None:
    data = np.load(FIXTURES / "dflash2_selector_full.npz", allow_pickle=False)
    fixture = load_fixture(FIXTURES / "dflash2_selector_path.json")

    result = candidate_selector_select(
        fixture.inputs["hidden"],
        fixture.inputs["logits"],
        fixture.inputs["anchor_ids"],
        fixture.inputs["predecessor_codebook"],
        fixture.inputs["successor_codebook"],
        fixture.inputs["hidden_projection"],
        top_k=fixture.inputs["top_k"],
    )

    assert np.array_equal(result.path, data["path"])
    # torch.topk(sorted=False) returns the top-k values/indices in unspecified
    # order; numpy sorts descending. Compare value multisets per position.
    assert np.array_equal(np.sort(result.unary, axis=-1), np.sort(data["unary"].astype(np.float32), axis=-1))
    # Scores accumulate rank=8 dot products; allow fp32 rounding in the ordering.
    assert np.allclose(
        np.sort(result.scores, axis=-1),
        np.sort(data["scores"].astype(np.float32), axis=-1),
        atol=1e-5,
    )
    # torch.topk(sorted=False) candidate order is unspecified; compare as sets per position.
    for b in range(data["candidates"].shape[0]):
        for p in range(data["candidates"].shape[1]):
            assert set(result.candidates[b, p].tolist()) == set(data["candidates"][b, p].tolist()), (
                f"candidate set mismatch at ({b},{p})"
            )


def test_dflash2_selector_registered_and_resolvable() -> None:
    kernel = resolve(backend="cpu_reference", layer="dflash2_selector", quant="fp32")
    assert kernel is candidate_selector_select


def test_dflash2_grouped_conv_registered_and_resolvable() -> None:
    from hipengine.kernels.cpu_reference.dflash2 import grouped_dynamic_convolve

    kernel = resolve(backend="cpu_reference", layer="dflash2_grouped_conv", quant="fp32")
    assert kernel is grouped_dynamic_convolve


def test_dflash2_conv_requires_divisible_group_size() -> None:
    from hipengine.kernels.cpu_reference.dflash2 import grouped_dynamic_convolve

    hidden = np.zeros((1, 3, 32), dtype=np.float32)
    base = np.zeros((2, 32), dtype=np.float32)
    dynamic = np.zeros((1, 3, 2, 4), dtype=np.float32)
    with pytest.raises(ValueError, match="group_size 5 must divide"):
        grouped_dynamic_convolve(hidden, dynamic, base, group_size=5)


def test_dflash2_selector_rejects_shape_mismatch() -> None:
    hidden = np.zeros((1, 4, 16), dtype=np.float32)
    logits = np.zeros((1, 3, 40), dtype=np.float32)  # length mismatch
    with pytest.raises(ValueError, match="logits .* must match hidden"):
        candidate_selector_select(
            hidden,
            logits,
            np.array([0], dtype=np.int64),
            np.zeros((40, 8), dtype=np.float32),
            np.zeros((40, 8), dtype=np.float32),
            np.zeros((8, 16), dtype=np.float32),
            top_k=6,
        )
