"""D1 RED test: host-side DFlash2 numpy drafter vs the real reference model.

The golden trace was generated by ``scripts/gen_dflash2_drafter_golden.py``
running the actual ``DFlash2DraftModel`` (z-lab/dflash @ 07ebd93) in fp32 over
deterministic synthetic inputs. This test pins the exact drafter contract the
native D2 kernels must reproduce: identical final hidden, draft logits, and
greedy selector path / candidate tables.
"""

from __future__ import annotations

import inspect
from pathlib import Path

import numpy as np
import pytest

from hipengine.loading.dflash import dflash_draft_config_from_hf
from hipengine.loading.safetensors import load_weight_index
from hipengine.speculative.dflash2_drafter import DFlash2NumpyDrafter, load_dflash2_numpy_weights

SNAPSHOT = Path(
    "/home/lhl/.cache/huggingface/hub/models--z-lab--Qwen3.8-27B-DFlash2/snapshots/"
    "50307d4c4cde6860d4eee73e2547cd786fe8e8a4"
)
GOLDEN = Path(__file__).resolve().parent / "fixtures" / "cpu_reference" / "dflash2_drafter_golden.npz"

NEEDS_REF = SNAPSHOT.exists() and GOLDEN.exists()


def test_dflash2_native_api_uses_fixed_trained_block_geometry() -> None:
    from hipengine.speculative.dflash2_native import DFlash2NativeDrafter

    assert "bs" not in inspect.signature(DFlash2NativeDrafter.forward).parameters
    assert "rows" not in inspect.signature(DFlash2NativeDrafter.select).parameters
    assert "rows" not in inspect.signature(DFlash2NativeDrafter.last_candidates).parameters

    cycle_source = (
        Path(__file__).resolve().parents[1] / "scripts" / "dflash2_gguf_cycle.py"
    ).read_text()
    assert "DF2_FWD_BS" not in cycle_source
    assert "DF2_CYCLE_DEBUG" not in cycle_source


@pytest.mark.skipif(not NEEDS_REF, reason="Qwen3.8-27B-DFlash2 snapshot or golden trace not cached")
def test_dflash2_numpy_drafter_matches_reference_model() -> None:
    index = load_weight_index(SNAPSHOT)
    config = dflash_draft_config_from_hf(index.config)
    weights = load_dflash2_numpy_weights(index)
    drafter = DFlash2NumpyDrafter(config, weights)

    data = np.load(GOLDEN, allow_pickle=False)
    final_hidden = drafter.forward(
        data["target_hidden_concat"],
        data["noise_embedding"],
        data["position_ids"],
    )
    draft_hidden = final_hidden[:, 1 - config.block_size :, :]

    # The golden was emitted by torch while this oracle uses NumPy BLAS. The
    # current environment differs by at most 4.38e-4 in the 7x5120 hidden
    # tensor; logits, greedy path, and candidate sets below remain unchanged.
    assert np.allclose(
        draft_hidden,
        data["draft_hidden"].astype(np.float32),
        atol=5e-4,
        rtol=2e-4,
    ), f"draft hidden mismatch (max_abs={np.abs(draft_hidden - data['draft_hidden']).max():.3e})"

    proposal = drafter.propose(
        draft_hidden,
        data["output_head_weight"],
        data["anchor_ids"],
    )
    assert np.allclose(
        proposal.logits,
        data["logits"].astype(np.float32),
        atol=5e-2,
        rtol=1e-3,
    ), "draft logits mismatch"
    assert np.array_equal(
        proposal.path, data["path"]
    ), f"greedy path mismatch: {proposal.path.tolist()} vs {data['path'].tolist()}"

    # torch.topk(sorted=False) candidate order is unspecified; compare as sets.
    for p in range(proposal.candidates.shape[1]):
        assert set(proposal.candidates[0, p].tolist()) == set(data["candidates"][0, p].tolist()), (
            f"candidate set mismatch at position {p}"
        )


@pytest.mark.skipif(not SNAPSHOT.exists(), reason="Qwen3.8-27B-DFlash2 snapshot not cached")
def test_dflash2_numpy_weight_loader_roundtrip_shape() -> None:
    index = load_weight_index(SNAPSHOT)
    weights = load_dflash2_numpy_weights(index)

    assert weights["fc.weight"].shape == (5120, 25600)
    assert weights["candidate_selector.predecessor_codebook"].shape == (248320, 256)
    assert weights["layers.0.attention_conv.base_kernel"].shape == (2, 2, 5120)
    assert weights["layers.0.attention_conv.kernel_projection.weight"].shape == (1280, 5120)
    # BF16 payload values must be finite and in a plausible range.
    assert np.isfinite(weights["fc.weight"]).all()
    assert float(np.abs(weights["fc.weight"]).mean()) < 1.0


def test_dflash2_numpy_drafter_rejects_non_dflash2_config() -> None:
    cfg = dflash_draft_config_from_hf(_plain_draft_config())
    with pytest.raises(ValueError, match="not a DFlash2 drafter"):
        DFlash2NumpyDrafter(cfg, {})


def _plain_draft_config() -> dict:
    return {
        "architectures": ["DFlashDraftModel"],
        "dflash_config": {"mask_token_id": 99, "target_layer_ids": [1, 3]},
        "dtype": "bfloat16",
        "head_dim": 4,
        "hidden_size": 16,
        "intermediate_size": 32,
        "layer_types": ["full_attention", "full_attention"],
        "model_type": "qwen3",
        "num_attention_heads": 4,
        "num_hidden_layers": 2,
        "num_key_value_heads": 2,
        "num_target_layers": 4,
        "rope_theta": 10_000_000.0,
        "vocab_size": 100,
    }
