"""Tokenizer gate: the pure-Python BPE must reproduce the pinned tiktoken release.

The oracle corpus fixture is generated by ``scripts/yue2_oracle.py tokenizer``
with the release's own ``tiktoken.Encoding`` (same pattern, same ranks).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from hipengine.tokenization.yue2 import (
    ORDINARY_VOCAB,
    PATTERN,
    SPECIAL_NAMES,
    YuE2TextTokenizer,
)

FIXTURES = Path(__file__).parent / "fixtures/yue2/tokenizer"
CACHE = Path.home() / ".cache/huggingface/hub"
MODEL_DIRS = sorted(CACHE.glob("models--m-a-p--YuE2-3B/snapshots/*"))


def _model_dir() -> Path:
    for directory in MODEL_DIRS:
        if (directory / "qwen.tiktoken").is_file():
            return directory
    pytest.skip("YuE2-3B checkpoint not present in the local Hugging Face cache")


@pytest.fixture(scope="module")
def tokenizer() -> YuE2TextTokenizer:
    return YuE2TextTokenizer(_model_dir() / "qwen.tiktoken")


def test_special_token_table_matches_release():
    assert len(SPECIAL_NAMES) == 208
    assert SPECIAL_NAMES[:8] == (
        "<|endoftext|>",
        "<|im_start|>",
        "<|im_end|>",
        "<R>",
        "<S>",
        "<X>",
        "<mask>",
        "<sep>",
    )
    assert SPECIAL_NAMES[204:206] == ("<abc>", "</abc>")
    assert SPECIAL_NAMES[206] == "<extra_198>"
    assert PATTERN.startswith(r"(?i:'s|'t|'re|'ve|'m|'ll|'d)")


def test_tokenizer_identity_and_vocab(tokenizer):
    assert tokenizer.identity.ranks == ORDINARY_VOCAB
    assert tokenizer.n_vocab == ORDINARY_VOCAB + 208
    assert tokenizer.identity.sha256 == json.loads(
        (FIXTURES / "manifest.json").read_text()
    )["merge_sha256"]
    assert tokenizer.specials["<abc>"] == ORDINARY_VOCAB + 204


def test_tokenizer_rejects_wrong_rank_count(tmp_path):
    bad = tmp_path / "qwen.tiktoken"
    bad.write_bytes(b"YQ== 0\n")
    with pytest.raises(ValueError):
        YuE2TextTokenizer(bad)
    with pytest.raises(FileNotFoundError):
        YuE2TextTokenizer(tmp_path / "missing.tiktoken")


def test_encode_matches_pinned_tiktoken_corpus(tokenizer):
    manifest = json.loads((FIXTURES / "manifest.json").read_text())
    data = np.load(FIXTURES / "corpus.npz")
    checked = 0
    for index in range(manifest["cases"]):
        text = data[f"text_{index}"].tobytes().decode("utf-8")
        expected = data[f"ids_{index}"].tolist()
        assert tokenizer.encode(text) == expected, f"case {index}: {text[:40]!r}"
        # Round-trip through the byte decoder.
        assert tokenizer.decode(expected) == text
        checked += 1
    assert checked == manifest["cases"] >= 20


def test_encode_is_ordinary_only(tokenizer):
    # Special tokens are ordinary text to ``encode``: they are never emitted.
    text = "<|endoftext|><abc><extra_0>"
    ids = tokenizer.encode(text)
    assert all(0 <= token < ORDINARY_VOCAB for token in ids)
    assert tokenizer.decode(ids) == text


def test_encode_normalizes_nfc(tokenizer):
    decomposed = "cafe\u0301"
    composed = "caf\u00e9"
    assert tokenizer.encode(decomposed) == tokenizer.encode(composed)


def test_encode_rejects_non_strings(tokenizer):
    with pytest.raises(TypeError):
        tokenizer.encode(b"bytes")


def test_lyrics_and_abc_encodings_are_stable(tokenizer):
    """Real protocol strings must tokenize without special-token leakage."""
    from hipengine.generation.yue2 import ABC_START, EOD, SongRequest, token_prefixes

    request = SongRequest(
        style="Warm acoustic pop, clear lead vocal",
        lyrics="[Verse]\nMorning light across the floor\n[Chorus]\nCarry on into the blue",
        cot="full",
        seed=1234,
    )
    prefix = token_prefixes(request, tokenizer.encode)
    assert prefix[0] == EOD
    assert prefix[-1] == ABC_START
    # Only the appended delimiters may exceed the ordinary vocabulary.
    assert all(0 <= token < EOD for token in prefix[1:-1])
    # Mandarin lyrics stay inside the ordinary vocabulary.
    mandarin = SongRequest(style="Mandarin pop", lyrics="清晨的光落在窗前", cot="off")
    ids = tokenizer.encode(mandarin.text())
    assert ids and all(0 <= token < EOD for token in ids)
    assert tokenizer.decode(ids) == mandarin.text()
