"""gfx1100 linear-attention kernel wrappers."""

from hipengine.kernels.hip_gfx1100.linear_attn.conv import (
    build_qwen35_linear_attn_conv,
    plan_qwen35_linear_attn_conv_build,
    qwen35_linear_attn_conv_decode_bf16,
    qwen35_linear_attn_conv_decode_f32,
    qwen35_linear_attn_conv_decode_fp16,
    qwen35_linear_attn_conv_prefill_f32,
    qwen35_linear_attn_conv_prefill_fp16,
    qwen35_linear_attn_conv_prefill_segments_f32,
    qwen35_linear_attn_tree_conv_decode_bf16_tloop,
    qwen35_linear_attn_tree_conv_decode_fp16_tloop,
    register_qwen35_linear_attn_conv_kernels,
)
from hipengine.kernels.hip_gfx1100.linear_attn.gdn import (
    build_qwen35_linear_attn_gdn,
    plan_qwen35_linear_attn_gdn_build,
    qwen35_gdn_prefill_recurrent_f32,
    qwen35_gdn_prefill_recurrent_k2_f32,
    qwen35_gdn_prefill_recurrent_segments_k2_f32,
    qwen35_gdn_prefill_rmsnorm_gate_bf16,
    qwen35_gdn_prefill_rmsnorm_gate_fp16,
    qwen35_gdn_prefill_rmsnorm_gate_rotate_fp16,
    qwen35_gdn_recurrent_rmsnorm_gate_lowp_bf16,
    qwen35_gdn_recurrent_rmsnorm_gate_lowp_fp16,
    qwen35_gdn_tree_recurrent_rmsnorm_gate_lowp_tloop_bf16,
    qwen35_gdn_tree_recurrent_rmsnorm_gate_lowp_tloop_fp16,
    qwen35_linear_attn_prefill_prepare_f32_bf16,
    qwen35_linear_attn_prefill_prepare_f32_fp16,
    register_qwen35_linear_attn_gdn_kernels,
)

__all__ = [
    "build_qwen35_linear_attn_conv",
    "build_qwen35_linear_attn_gdn",
    "plan_qwen35_linear_attn_conv_build",
    "plan_qwen35_linear_attn_gdn_build",
    "qwen35_gdn_prefill_recurrent_f32",
    "qwen35_gdn_prefill_recurrent_k2_f32",
    "qwen35_gdn_prefill_recurrent_segments_k2_f32",
    "qwen35_gdn_prefill_rmsnorm_gate_bf16",
    "qwen35_gdn_prefill_rmsnorm_gate_fp16",
    "qwen35_gdn_prefill_rmsnorm_gate_rotate_fp16",
    "qwen35_gdn_recurrent_rmsnorm_gate_lowp_bf16",
    "qwen35_gdn_recurrent_rmsnorm_gate_lowp_fp16",
    "qwen35_linear_attn_prefill_prepare_f32_bf16",
    "qwen35_linear_attn_prefill_prepare_f32_fp16",
    "qwen35_gdn_tree_recurrent_rmsnorm_gate_lowp_tloop_bf16",
    "qwen35_gdn_tree_recurrent_rmsnorm_gate_lowp_tloop_fp16",
    "qwen35_linear_attn_conv_decode_bf16",
    "qwen35_linear_attn_conv_decode_f32",
    "qwen35_linear_attn_conv_decode_fp16",
    "qwen35_linear_attn_conv_prefill_f32",
    "qwen35_linear_attn_conv_prefill_fp16",
    "qwen35_linear_attn_conv_prefill_segments_f32",
    "qwen35_linear_attn_tree_conv_decode_bf16_tloop",
    "qwen35_linear_attn_tree_conv_decode_fp16_tloop",
    "register_qwen35_linear_attn_conv_kernels",
    "register_qwen35_linear_attn_gdn_kernels",
]
