"""gfx1100 speculative decoding kernel wrappers."""

from hipengine.kernels.hip_gfx1100.speculative.dflash_accept import (
    build_dflash_accept,
    dflash_accept_chain_i32,
    plan_dflash_accept_build,
    register_dflash_accept_kernels,
)
from hipengine.kernels.hip_gfx1100.speculative.dflash_commit import (
    build_dflash_commit,
    dflash_commit_chain_i32,
    linear_state_pair_commit_i32,
    plan_dflash_commit_build,
    register_dflash_commit_kernels,
)
from hipengine.kernels.hip_gfx1100.speculative.dflash_drafter import (
    build_dflash_drafter,
    dflash_add_bf16,
    dflash_concat_rows_bf16,
    dflash_concat_rows_f32,
    dflash_dense_bf16_to_bf16,
    dflash_dense_bf16_to_f32,
    dflash_gqa_attention_f32_bf16,
    dflash_head_rmsnorm_rotary_f32,
    dflash_key_rmsnorm_rotary_f32,
    dflash_prepare_noise_inputs_bf16_i32,
    dflash_prepare_noise_inputs_f16_to_bf16_i32,
    dflash_rmsnorm_bf16,
    dflash_silu_mul_bf16,
    dflash_update_kv_metadata_i32,
    plan_dflash_drafter_build,
    register_dflash_drafter_kernels,
)
from hipengine.kernels.hip_gfx1100.speculative.mtp import (
    build_mtp_speculative,
    mtp_accumulate_route_bf16_to_f32,
    mtp_accumulate_sigmoid_gate_bf16_to_f32,
    mtp_add_rmsnorm_bf16_oneplus,
    mtp_finalize_f32_to_bf16,
    mtp_fuse_inputs_f16_bf16,
    mtp_gate_mul_bf16,
    mtp_rmsnorm_bf16_oneplus,
    mtp_softmax_topk_f32,
    mtp_split_q_gate_f32_bf16,
    plan_mtp_speculative_build,
    register_mtp_speculative_kernels,
)

__all__ = [
    "build_dflash_accept",
    "build_dflash_commit",
    "build_dflash_drafter",
    "dflash_accept_chain_i32",
    "dflash_add_bf16",
    "dflash_concat_rows_bf16",
    "dflash_concat_rows_f32",
    "dflash_commit_chain_i32",
    "linear_state_pair_commit_i32",
    "dflash_dense_bf16_to_bf16",
    "dflash_dense_bf16_to_f32",
    "dflash_gqa_attention_f32_bf16",
    "dflash_head_rmsnorm_rotary_f32",
    "dflash_key_rmsnorm_rotary_f32",
    "dflash_prepare_noise_inputs_bf16_i32",
    "dflash_prepare_noise_inputs_f16_to_bf16_i32",
    "dflash_rmsnorm_bf16",
    "dflash_silu_mul_bf16",
    "dflash_update_kv_metadata_i32",
    "build_mtp_speculative",
    "mtp_accumulate_route_bf16_to_f32",
    "mtp_accumulate_sigmoid_gate_bf16_to_f32",
    "mtp_add_rmsnorm_bf16_oneplus",
    "mtp_finalize_f32_to_bf16",
    "mtp_fuse_inputs_f16_bf16",
    "mtp_gate_mul_bf16",
    "mtp_rmsnorm_bf16_oneplus",
    "mtp_softmax_topk_f32",
    "mtp_split_q_gate_f32_bf16",
    "plan_dflash_accept_build",
    "plan_dflash_commit_build",
    "plan_dflash_drafter_build",
    "plan_mtp_speculative_build",
    "register_dflash_accept_kernels",
    "register_dflash_commit_kernels",
    "register_dflash_drafter_kernels",
    "register_mtp_speculative_kernels",
]
