"""gfx1100 dense linear kernel wrappers."""

from hipengine.kernels.hip_gfx1100.linear.dense_gemv import (
    build_dense_gemv,
    dense_dual_gemv_out_bf16,
    dense_dual_gemv_out_bf16_wmma,
    dense_dual_gemv_out_fp16,
    dense_dual_gemv_out_fp16_wmma,
    dense_dual_gemv_separate_out_bf16,
    dense_dual_gemv_separate_out_fp16,
    dense_gemv_out_bf16,
    dense_gemv_out_bf16_wmma,
    dense_gemv_out_fp16,
    dense_gemv_out_fp16_wmma,
    plan_dense_gemv_build,
    register_dense_gemv_kernels,
)
from hipengine.kernels.hip_gfx1100.linear.lm_head import (
    argmax_f32,
    argmax_f32_rows_i32,
    build_lm_head,
    lm_head_argmax_stage1_blocks,
    lm_head_fp16_argmax_bf16,
    lm_head_fp16_argmax_bf16_rows_i32,
    plan_lm_head_build,
    register_lm_head_kernels,
    topk_f32_rows_i32,
    w8a16_lm_head_argmax_rows_bf16,
)

__all__ = [
    "build_dense_gemv",
    "dense_dual_gemv_out_bf16",
    "dense_dual_gemv_out_bf16_wmma",
    "dense_dual_gemv_out_fp16",
    "dense_dual_gemv_out_fp16_wmma",
    "dense_dual_gemv_separate_out_bf16",
    "dense_dual_gemv_separate_out_fp16",
    "dense_gemv_out_bf16",
    "dense_gemv_out_bf16_wmma",
    "dense_gemv_out_fp16",
    "dense_gemv_out_fp16_wmma",
    "plan_dense_gemv_build",
    "register_dense_gemv_kernels",
    "argmax_f32",
    "argmax_f32_rows_i32",
    "build_lm_head",
    "lm_head_argmax_stage1_blocks",
    "lm_head_fp16_argmax_bf16",
    "lm_head_fp16_argmax_bf16_rows_i32",
    "plan_lm_head_build",
    "register_lm_head_kernels",
    "topk_f32_rows_i32",
    "w8a16_lm_head_argmax_rows_bf16",
]
