"""Quant plugins and registry."""

from hipengine.quant.base import QuantPlugin
from hipengine.quant.bf16 import BF16, BF16Quant
from hipengine.quant.fp16 import FP16, FP16Quant
from hipengine.quant.gguf import (
    GGMLQuantizationType,
    GGUFQuantLayout,
    GGUFValueType,
    GGUF_QUANT_LAYOUTS,
    QK_K,
    bf16_to_float32,
    dequantization_supported,
    dequantize_gguf_data,
    ggml_type,
    ggml_type_name,
    llama_file_type_name,
    nbytes_for_shape,
    quant_layout,
    quant_shape_from_byte_shape,
    quant_shape_to_byte_shape,
    unpack_q4_k_scale_min,
)
from hipengine.quant.gguf_k import (
    GGUFQ5KQuant,
    GGUFQ6KQuant,
    GGUFQ80Quant,
    GGUF_Q5_K,
    GGUF_Q6_K,
    GGUF_Q8_0,
)
from hipengine.quant.gguf_q4_k import (
    GGUF_Q4_K,
    GGUF_Q4_K_BLOCK_BYTES,
    GGUF_Q4_K_PACK,
    GGUF_Q4_K_SUBBLOCK,
    GGUF_Q4_K_SUBBLOCKS,
    GGUFQ4KPack8,
    GGUFQ4KQuant,
    awq_pack8_shift_for_lane,
    repack_gguf_q4_k_pack8,
)
from hipengine.quant.w4_paro import W4_PARO, W4ParoQuant
from hipengine.quant.registry import (
    DuplicateQuantError,
    MissingQuantError,
    register_quant,
    registered_quants,
    resolve_quant,
)

__all__ = [
    "BF16",
    "BF16Quant",
    "DuplicateQuantError",
    "FP16",
    "FP16Quant",
    "GGMLQuantizationType",
    "GGUFQ4KPack8",
    "GGUFQ4KQuant",
    "GGUFQ5KQuant",
    "GGUFQ6KQuant",
    "GGUFQ80Quant",
    "GGUFQuantLayout",
    "GGUFValueType",
    "GGUF_QUANT_LAYOUTS",
    "GGUF_Q4_K",
    "GGUF_Q4_K_BLOCK_BYTES",
    "GGUF_Q4_K_PACK",
    "GGUF_Q4_K_SUBBLOCK",
    "GGUF_Q4_K_SUBBLOCKS",
    "GGUF_Q5_K",
    "GGUF_Q6_K",
    "GGUF_Q8_0",
    "MissingQuantError",
    "QuantPlugin",
    "QK_K",
    "W4ParoQuant",
    "W4_PARO",
    "awq_pack8_shift_for_lane",
    "bf16_to_float32",
    "dequantization_supported",
    "dequantize_gguf_data",
    "ggml_type",
    "ggml_type_name",
    "llama_file_type_name",
    "nbytes_for_shape",
    "quant_layout",
    "quant_shape_from_byte_shape",
    "quant_shape_to_byte_shape",
    "register_quant",
    "repack_gguf_q4_k_pack8",
    "registered_quants",
    "resolve_quant",
    "unpack_q4_k_scale_min",
]
