"""Surya fp32 text-decoder GPU kernels (gfx1100/gfx1151 JIT)."""

from hipengine.kernels.hip_gfx1100.surya.surya_ops import (
    SURYA_DECODE_HEAD_DIM,
    SURYA_DECODE_Q_PER_KV,
    SURYA_SPAN_BLOCK_SIZE,
    SURYA_SPLIT_ALIGNMENT,
    SURYA_TARGET_SPLITS,
    SuryaDenseSpanPlan,
    build_surya_ops,
    plan_surya_decode_splits,
    plan_surya_dense_spans,
    plan_surya_ops_build,
    surya_causal_mask_scale_f32,
    surya_full_attn_decode_f32_spans,
    surya_gdn_l2norm_f32,
    surya_rmsnorm_f32,
    surya_scatter_kv_f32,
    surya_scatter_kv_f32_spans,
    surya_split_qgate_f32,
)

__all__ = [
    "SURYA_DECODE_HEAD_DIM",
    "SURYA_DECODE_Q_PER_KV",
    "SURYA_SPAN_BLOCK_SIZE",
    "SURYA_SPLIT_ALIGNMENT",
    "SURYA_TARGET_SPLITS",
    "SuryaDenseSpanPlan",
    "build_surya_ops",
    "plan_surya_decode_splits",
    "plan_surya_dense_spans",
    "plan_surya_ops_build",
    "surya_causal_mask_scale_f32",
    "surya_full_attn_decode_f32_spans",
    "surya_gdn_l2norm_f32",
    "surya_rmsnorm_f32",
    "surya_scatter_kv_f32",
    "surya_scatter_kv_f32_spans",
    "surya_split_qgate_f32",
]
