"""Generation registries and built-in torch-free generation paths."""

from hipengine.generation.batch_scheduler import (
    BatchGenerateRequest,
    CompactPromptBucket,
    CompactPromptSlab,
    CompletedRequest,
    GeneratedToken,
    GeneratedTokenEvent,
    GRAPH_KERNEL_TIME_HISTOGRAM_BUCKETS,
    GraphBucketCache,
    GraphBucketStats,
    PerRowSamplingParams,
    RequestObservability,
    ResidentBatchScheduler,
    SamplerParamsBlock,
    SPECULATIVE_TARGET_COMPATIBLE_SAMPLING_MODES,
    SPECULATIVE_TARGET_SAMPLING_POLICY,
    SpeculativeCommitPlan,
    SpeculativeStateCommitPlan,
    SpeculativeVerifyBufferPlan,
    SpeculativeVerifyPlan,
    SpeculativeVerifyWork,
)
from hipengine.generation.constraints import (
    ForcedTokenQueue,
    JsonObjectConstraintState,
    ThinkingBudgetState,
    TokenSequenceDFAState,
    normalize_token_sequences,
    token_sequence_state_for_tokens,
)
from hipengine.generation.deadline import (
    GenerationCancellationToken,
    GenerationCancelled,
    GenerationDeadlineExceeded,
    generation_deadline_expired,
    raise_if_generation_cancelled,
    raise_if_generation_deadline_expired,
)
from hipengine.generation.engine_loop import (
    PREFILL_DECODE_POLICIES,
    EngineLoopConfig,
    EngineLoopEvent,
    EngineLoopRunner,
    ResidentEngineLoop,
    SubmitPollTextGenerator,
    add_engine_loop_config_args,
    engine_loop_config_from_args,
    engine_loop_config_from_env,
)
from hipengine.generation.registry import (
    DecodePhase,
    DecodeState,
    DuplicateGeneratorError,
    FinishDetails,
    GenerationTelemetry,
    GenerationKey,
    GenerationOutput,
    GenerationRequest,
    GenerationStreamChunk,
    MissingGeneratorError,
    TextGenerator,
    TokenLogprob,
    clear_generation_registry_for_tests,
    register_text_generator,
    registered_text_generators,
    resolve_text_generator,
)
from hipengine.generation.sampling import (
    NATIVE_GPU_SAMPLER_UNSUPPORTED_CAPABILITIES,
    RowSamplingState,
    SampleResult,
    SamplerPlan,
    SamplingMode,
    SPECULATIVE_MTP_INCOMPATIBLE_CONDITIONS,
    SPECULATIVE_MTP_INCOMPATIBLE_FIELDS,
    active_processor_names,
    clone_thinking_budget_state,
    derive_row_seed,
    normalize_logit_bias_pairs,
    plan_sampler,
    row_seed_for_index,
    sampler_fast_path_blockers,
    select_token,
    speculative_mtp_sampling_blockers,
    thinking_budget_active,
    thinking_budget_state_from_params,
    supports_native_gpu_sampling,
    supports_speculative_mtp_sampling,
    validate_sampling_params,
)

_BUILTINS_REGISTERED = False


def register_builtin_generators() -> None:
    """Register built-in generation paths lazily.

    Importing ``hipengine`` must remain light and torch-free, so model-specific runtime
    generation modules are imported only when the public API needs generation.
    """

    global _BUILTINS_REGISTERED
    if _BUILTINS_REGISTERED:
        return
    from hipengine.generation import qwen35_gguf as _qwen35_gguf  # noqa: F401
    from hipengine.generation import qwen35_paro as _qwen35_paro  # noqa: F401

    _BUILTINS_REGISTERED = True


__all__ = [
    "BatchGenerateRequest",
    "CompactPromptBucket",
    "CompactPromptSlab",
    "CompletedRequest",
    "DecodePhase",
    "DecodeState",
    "DuplicateGeneratorError",
    "EngineLoopConfig",
    "EngineLoopEvent",
    "EngineLoopRunner",
    "FinishDetails",
    "ForcedTokenQueue",
    "GenerationCancellationToken",
    "GenerationCancelled",
    "GenerationDeadlineExceeded",
    "GenerationTelemetry",
    "GeneratedToken",
    "GeneratedTokenEvent",
    "GenerationKey",
    "GenerationOutput",
    "GRAPH_KERNEL_TIME_HISTOGRAM_BUCKETS",
    "GraphBucketCache",
    "GraphBucketStats",
    "GenerationRequest",
    "GenerationStreamChunk",
    "JsonObjectConstraintState",
    "MissingGeneratorError",
    "NATIVE_GPU_SAMPLER_UNSUPPORTED_CAPABILITIES",
    "PREFILL_DECODE_POLICIES",
    "PerRowSamplingParams",
    "RequestObservability",
    "ResidentBatchScheduler",
    "RowSamplingState",
    "SampleResult",
    "SamplerParamsBlock",
    "SamplerPlan",
    "SamplingMode",
    "SPECULATIVE_MTP_INCOMPATIBLE_CONDITIONS",
    "SPECULATIVE_MTP_INCOMPATIBLE_FIELDS",
    "SPECULATIVE_TARGET_COMPATIBLE_SAMPLING_MODES",
    "SPECULATIVE_TARGET_SAMPLING_POLICY",
    "ResidentEngineLoop",
    "SubmitPollTextGenerator",
    "SpeculativeCommitPlan",
    "SpeculativeStateCommitPlan",
    "SpeculativeVerifyBufferPlan",
    "SpeculativeVerifyPlan",
    "SpeculativeVerifyWork",
    "TextGenerator",
    "ThinkingBudgetState",
    "TokenSequenceDFAState",
    "TokenLogprob",
    "active_processor_names",
    "add_engine_loop_config_args",
    "clear_generation_registry_for_tests",
    "clone_thinking_budget_state",
    "derive_row_seed",
    "engine_loop_config_from_args",
    "engine_loop_config_from_env",
    "generation_deadline_expired",
    "normalize_token_sequences",
    "normalize_logit_bias_pairs",
    "plan_sampler",
    "register_builtin_generators",
    "register_text_generator",
    "registered_text_generators",
    "resolve_text_generator",
    "raise_if_generation_cancelled",
    "raise_if_generation_deadline_expired",
    "row_seed_for_index",
    "sampler_fast_path_blockers",
    "select_token",
    "speculative_mtp_sampling_blockers",
    "supports_native_gpu_sampling",
    "supports_speculative_mtp_sampling",
    "thinking_budget_active",
    "thinking_budget_state_from_params",
    "token_sequence_state_for_tokens",
    "validate_sampling_params",
]
