"""Small device-resident runtime state helpers."""

from hipengine.kernels.hip_gfx1100.runtime.state import (
    advance_decode_position_i64,
    advance_decode_positions_i64,
    build_runtime_state,
    embedding_lookup_batch_bf16_i64,
    embedding_lookup_batch_fp16_i64,
    embedding_lookup_batch_mapped_bf16_i64,
    embedding_lookup_batch_mapped_fp16_i64,
    embedding_lookup_bf16_i64,
    embedding_lookup_fp16_i64,
    plan_runtime_state_build,
    record_i64_scalar_indexed,
    register_runtime_state_kernels,
    set_decode_position_i64,
    set_decode_positions_i64,
    set_i64_scalar,
    set_i64_vector,
    unpack_verify_chain_dynamic_metadata_i64,
)

__all__ = [
    "advance_decode_position_i64",
    "advance_decode_positions_i64",
    "build_runtime_state",
    "embedding_lookup_batch_bf16_i64",
    "embedding_lookup_batch_fp16_i64",
    "embedding_lookup_batch_mapped_bf16_i64",
    "embedding_lookup_batch_mapped_fp16_i64",
    "embedding_lookup_bf16_i64",
    "embedding_lookup_fp16_i64",
    "plan_runtime_state_build",
    "record_i64_scalar_indexed",
    "register_runtime_state_kernels",
    "set_decode_position_i64",
    "set_decode_positions_i64",
    "set_i64_scalar",
    "set_i64_vector",
    "unpack_verify_chain_dynamic_metadata_i64",
]
